# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.IntegerField(unique=True, verbose_name='ID \u0427\u0430\u0442\u0430')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='UserTalker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=255, verbose_name='ID \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('status', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.UserTalker', verbose_name='ID \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a \u0447\u0430\u0442\u0430'),
        ),
    ]
