# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id_room',
            field=models.IntegerField(verbose_name='ID \u0427\u0430\u0442\u0430'),
        ),
    ]
