# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20170714_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='wayanswer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u043e\u0442\u0432\u0435\u0442\u0430'),
        ),
    ]
