# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatroom_wayanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id_room',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='id_user',
        ),
    ]
