# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20170722_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='id_room',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID \u0427\u0430\u0442\u0430'),
        ),
    ]
