# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chatroom_id_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id_room',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='ID \u0427\u0430\u0442\u0430'),
        ),
    ]
