# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_auto_20170726_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u043d\u0438\u044f'),
        ),
    ]
