# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_auto_20170727_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': '\u0427\u0430\u0442', 'verbose_name_plural': '\u0427\u0430\u0442'},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='wayanswer',
        ),
    ]
