# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_chatsetting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='title',
            field=models.CharField(default='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u0447\u0430\u0442 \u0431\u043e\u0442\u0430', max_length=50, verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438'),
        ),
    ]
