# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0013_auto_20170814_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconsultant',
            name='img',
            field=models.ImageField(blank=True, height_field=54, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e(54x54)', width_field=54),
        ),
    ]
