# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0014_auto_20170816_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSetting',
        ),
        migrations.AddField(
            model_name='chatconsultant',
            name='status',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0427\u0430\u0442\u0411\u043e\u0442\u0430'),
        ),
    ]
