# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0015_auto_20171005_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconsultant',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='\u0424\u0418\u041e \u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430'),
        ),
    ]
