# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('quest', models.TextField(blank=True, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043e\u0442 \u043f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u0435\u0439',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043e\u0442 \u043f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u0435\u0439',
            },
        ),
    ]
