# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo', '0003_seo_words_alias'),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='seo',
        ),
        migrations.AddField(
            model_name='production',
            name='seo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_seo.SEO_Words'),
            preserve_default=False,
        ),
    ]
