# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo', '0003_seo_words_alias'),
        ('base_app', '0002_auto_20171008_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='seo',
        ),
        migrations.AddField(
            model_name='production',
            name='seo',
            field=models.ManyToManyField(to='django_seo.SEO_Words'),
        ),
    ]
